### ISSUE TITLE
`declarativeNetRequest` missing and beta features in general

### ISSUE THREAD

**Issue by maphe** [GoogleChrome/chrome-types#10]
`chrome.declarativeNetRequest` does not seem to be present in `chrome-types` while it's fairly well documented in the Manifest V3 section.

I'm wondering if it's because the feature is still flagged as beta (http://ext.123456cc.cc/static/chromeAPI/declarativeNetRequest.htm) and this lib seems to be auto generated.

Is there any chance `chrome-types` generates multiple packages so it's possible to use beta features as dependencies? I'm thinking something like `chrome-types-beta` and/or `chrome-types-dev`.

**Comment by samthor** [comment]
This is actually now in the latest published version.
