### ISSUE TITLE
Property 'ShowAction' does not exist on type 'typeof declarativeContent' ts(2339)

### ISSUE THREAD

**Issue by blemoine167** [GoogleChrome/chrome-types#16]
Hello,

I'm trying to migrate an extension to manifest v3 and the following error popped up on compilation :
`Property 'ShowAction' does not exist on type 'typeof declarativeContent' ts(2339)`

Related code is :
```javascript
// Manifest V3
chrome.runtime.onInstalled.addListener(() => {
  chrome.declarativeContent.onPageChanged.removeRules(undefined, () => {
    chrome.declarativeContent.onPageChanged.addRules([
      {
        conditions: [
          new chrome.declarativeContent.PageStateMatcher({
            pageUrl: {hostSuffix: '.example.com'},
          })
        ],
        actions: [new chrome.declarativeContent.ShowAction()]
      }
    ]);
  });
});
```
(code found in https://developer.chrome.com/blog/mv3-actions/)

**Comment by samthor** [comment]
@blemoine167 This will eventually show up as fixed in Chrome, as it was fixed there: https://chromium-review.googlesource.com/c/chromium/src/+/3221609

Probably in 95 or 96.
