### ISSUE TITLE
Determine API release versions

### ISSUE THREAD

**Issue by samthor** [GoogleChrome/chrome-types#3]
We generally only care about release versions within 15-20 releases. We should annotate generated types with this.

**Comment by tophf** [comment]
This info is helpful for us extension authors as we often keep our extensions compatible with older versions of Chrome, not just 15-20 versions back. If this repository is aimed to help us, extension authors, then it would make sense to preserve the existing version history, which already covers ~50 versions back (v35 is the earliest used in API json in chromium source code).
