### ISSUE TITLE
Expose version support for methods that return promises

### ISSUE THREAD

**Issue by dotproto** [GoogleChrome/chrome-types#35]
_This is necessary for GoogleChrome/developer.chrome.com#2117_

The Chrome team is progressively adding support for Promises in Manifest V3 APIs. At the moment we flag methods that return promises, but don't indicate when promise support landed. This makes it difficult (if not practically impossible) for developers that support a range of Chrome versions to know whether it's safe for them to expect a given method to return a promise or whether they'll be introducing bugs into their product in old versions of Chrome.

For each method that returns a Promise, this project should emit the first version of Chrome that shipped with promise support.

This feature request can be generalized to expose version information for ANY change to a type, both added and removed properties.

**Comment by MichaelSolati** [comment]
@dotproto I have a vested interest in this so I dug into it a bit... 

1) As of now @samthor 's code is automatically making callbacks to promises, none of the promises are being generated according to the IDLs. 
2) The [`'tools/json_schema_compiler/idl_schema.py'` ](https://chromium.googlesource.com/chromium/src/+/69.0.3497.128/tools/json_schema_compiler/idl_schema.py) doesn't seem to care about the [`[supportsPromises]`](https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/extensions/api/scripting.idl;l=197) as it's not being included in the generated JSONs. This would need to be resolved first.
3) The next issue would have to do with getting the version number as [`_maybeExpandFunctionReturnsAsync`](https://github.com/MichaelSolati/chrome-types/blob/8ba5062952301099716c95326f61d3503112a2be/tools/lib/traverse.js#L144) (which takes a spec and adds the Promise to it) doesn't seem to have access to the version where it was first detected. However @samthor may know when/where this can be injected.
