### ISSUE TITLE
Difference to `@types/chrome`

### ISSUE THREAD

**Issue by AngeloCore** [GoogleChrome/chrome-types#47]
What is the difference between `chrome-types` and [`@types/chrome`](http://npmjs.com/@types/chrome)? Why are there 2 chrome typings packages?

**Comment by mansurov1024** [comment]
The difference for me - the last one works. After adding `chrome-types` still get 

> error TS2304: Cannot find name 'chrome'.

With the  [@types/chrome](http://npmjs.com/@types/chrome) this error disappears.

Also, if you have errors like 

> error TS2304: Cannot find name 'Blob'.

 you should add 

```json
{
  "compilerOptions": {
    "lib": ["dom"]
  }
}
```
to your tsconfig.json.

**Comment by oliverdunk** [comment]
`@types/chrome` is a community project which lives here: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/chrome. As far as I know, it is maintained manually.

`chrome-types` is automatically generated from the definitions inside of the Chromium source code. It exists primarily as part of the process for generating our documentation, but you're welcome to use it if it meets your needs.
