### ISSUE TITLE
Problem when instantiating a exp: new Date('2021-01-01') in some situations

### ISSUE THREAD

**Issue by SouzaHenrique** [GoogleChrome/chrome-types#8]
Hello everyone,

First of all, I don't really know if this is the correct place to post this, but the case is the following:

When instantiating a new Date() in the crhome console using javascript, for example, with the values '2021-01-01' the result is as it follows in the image bellow:

![IMG1](https://user-images.githubusercontent.com/39593434/105405691-31ced900-5c0a-11eb-977c-085957466a34.jpeg)

But, and correct if I'm wrong, the correct value should be, when considering that I'm from São Paulo - Brazil:
![image](https://user-images.githubusercontent.com/39593434/105405821-5aef6980-5c0a-11eb-930d-ccc2a9bb31d1.png)

The differences between the environment of the two images above is:
- In the first image we're using windows 8.1
- In the second image we're using windows 10
-all the screenshots has been taked in the same location
- Notice that the chrome versiong in the both of images are the same, 88.0.4324.104:

in windows 8:
![image](https://user-images.githubusercontent.com/39593434/105406341-0c8e9a80-5c0b-11eb-80ea-373ba275a626.png)

in windows 10:
![image](https://user-images.githubusercontent.com/39593434/105406403-24661e80-5c0b-11eb-8f6c-e0116d53a7c0.png)

**Comment by SouzaHenrique** [comment]
Relates to:
https://bugs.chromium.org/p/chromium/issues/detail?id=1169325

**Comment by samthor** [comment]
Sorry, this is not the right place for this issue—crbug is, and it seems like it's been filed there already.
