### ISSUE TITLE
visitItem.isLocal is missing from chrome.history.VisitItem

### ISSUE THREAD

**Issue by remusris** [GoogleChrome/chrome-types#85]
For some reason the `isLocal` is missing from the `chrome.history.VisitItem` type

https://developer.chrome.com/docs/extensions/reference/api/history#type-VisitItem

**Comment by oliverdunk** [comment]
Hmm, are you sure you are using an updated package? If you visit https://unpkg.com/chrome-types@0.1.324/index.d.ts and search for "visititem {", you can see the property there.
